##############################################################################
# Copyright (c) 2017-2023, Lawrence Livermore National Security, LLC and BLT
# project contributors. See the LICENSE file for details.
##############################################################################

variables:
  PROJECT_ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_PROJECT_DIR}
  LLNL_SERVICE_USER: atk
  CUSTOM_CI_BUILDS_DIR: /usr/workspace/atk/gitlab-runner

stages:
  - allocate
  - build
  - release

####
# Template
.build_script:
  script:
    #Use pre-existing allocation if any
    - JOBID=$(if [[ $SYS_TYPE = toss_* ]]; then squeue -h --name=${PROJECT_ALLOC_NAME} --format=%A; fi)
    - ASSIGN_ID=$(if [[ -n "${JOBID}" ]]; then echo "--jobid=${JOBID}"; fi)
   #BUILD + TEST
    - echo -e "section_start:$(date +%s):build_and_test\r\e[0K
      Build and test ${CI_PROJECT_NAME}"
    - ${ALLOC_COMMAND} .gitlab/build_and_test.sh
    - echo -e "section_end:$(date +%s):build_and_test\r\e[0K"
  artifacts:
    reports:
      junit: build/junit.xml


# This is where jobs are included
include:
  - local: .gitlab/build_lassen.yml
  - local: .gitlab/build_quartz.yml
# white238: Turned off while tioga is down for maintenance and is fickle
#  - local: .gitlab/build_tioga.yml
